"""Tests for the writer module."""

from __future__ import annotations

from pathlib import Path

from skillgen.models import (
    GenerationResult,
    OutputFormat,
    PatternCategory,
    SkillDefinition,
)
from skillgen.writer import (
    _format_agents_md_section,
    _format_combined_claude_skill,
    write_skills,
)


def _make_skill(
    category: PatternCategory,
    content: str = "",
    glob_patterns: list[str] | None = None,
) -> SkillDefinition:
    """Helper to create a SkillDefinition for testing."""
    return SkillDefinition(
        name=category.skill_name,
        description=category.description,
        category=category,
        content=content
        or f"<!-- Confidence: HIGH -->\n\nSample {category.display_name} content.\n\n### Subsection\n- pattern",
        languages=["Python"],
        glob_patterns=glob_patterns or ["*.py", "*.pyi"],
        always_apply=category.always_apply,
    )


def _make_generation(*categories: PatternCategory) -> GenerationResult:
    """Create a GenerationResult with skills for the given categories."""
    skills = [_make_skill(cat) for cat in categories]
    return GenerationResult(
        skills=skills,
        stats={"skills_generated": len(skills)},
        timing_seconds=0.1,
    )


class TestCombinedClaudeSkill:
    """Test the combined SKILL.md output format."""

    def test_output_path_is_project_conventions_skill_md(self, tmp_path: Path) -> None:
        generation = _make_generation(PatternCategory.NAMING)
        written = write_skills(generation, tmp_path, OutputFormat.CLAUDE)
        assert len(written) == 1
        assert (
            written[0].path == tmp_path / ".claude" / "skills" / "project-conventions" / "SKILL.md"
        )

    def test_frontmatter_has_required_fields(self) -> None:
        generation = _make_generation(PatternCategory.NAMING, PatternCategory.STYLE)
        content = _format_combined_claude_skill(generation)
        assert "name: project-conventions" in content
        assert "user-invocable: false" in content
        assert "paths:" in content
        assert "description:" in content

    def test_frontmatter_description_under_250_chars(self) -> None:
        generation = _make_generation(PatternCategory.NAMING)
        content = _format_combined_claude_skill(generation)
        desc_value = None
        for line in content.split("\n"):
            if line.startswith("description:"):
                desc_value = line[len("description:") :].strip()
                break
        assert desc_value is not None, "No description: line found in frontmatter"
        assert len(desc_value) <= 250, f"Description too long ({len(desc_value)} chars)"

    def test_paths_derived_from_glob_patterns(self) -> None:
        generation = _make_generation(PatternCategory.NAMING)
        generation.skills[0].glob_patterns = ["*.py", "*.pyi"]
        content = _format_combined_claude_skill(generation)
        assert "*.py" in content
        assert "*.pyi" in content

    def test_has_project_conventions_h1(self) -> None:
        generation = _make_generation(PatternCategory.NAMING)
        content = _format_combined_claude_skill(generation)
        assert "\n# Project Conventions\n" in content

    def test_categories_are_h2_sections(self) -> None:
        generation = _make_generation(PatternCategory.NAMING, PatternCategory.STYLE)
        content = _format_combined_claude_skill(generation)
        assert "\n## Naming Conventions\n" in content
        assert "\n## Code Style\n" in content

    def test_no_heading_inversion(self) -> None:
        """No ## followed by # within the content."""
        generation = _make_generation(
            PatternCategory.NAMING, PatternCategory.ERROR_HANDLING, PatternCategory.STYLE
        )
        content = _format_combined_claude_skill(generation)
        lines = content.split("\n")
        last_heading_level = 0
        for line in lines:
            if line.startswith("# ") and not line.startswith("## "):
                current_level = 1
            elif line.startswith("## ") and not line.startswith("### "):
                current_level = 2
            elif line.startswith("### "):
                current_level = 3
            else:
                continue
            if last_heading_level >= 2 and current_level == 1:
                msg = f"Heading inversion: h{last_heading_level} followed by h1: {line}"
                raise AssertionError(msg)
            last_heading_level = current_level

    def test_has_skillgen_header_comment(self) -> None:
        generation = _make_generation(PatternCategory.NAMING)
        content = _format_combined_claude_skill(generation)
        assert content.startswith("<!-- Generated by skillgen")

    def test_file_written_to_disk(self, tmp_path: Path) -> None:
        generation = _make_generation(PatternCategory.NAMING, PatternCategory.STYLE)
        write_skills(generation, tmp_path, OutputFormat.CLAUDE)
        skill_path = tmp_path / ".claude" / "skills" / "project-conventions" / "SKILL.md"
        assert skill_path.exists()
        content = skill_path.read_text(encoding="utf-8")
        assert "name: project-conventions" in content
        assert "## Naming Conventions" in content
        assert "## Code Style" in content


class TestClaudeCleanup:
    """Test cleanup of old flat skill files."""

    def test_removes_old_flat_skill_files(self, tmp_path: Path) -> None:
        skills_dir = tmp_path / ".claude" / "skills"
        skills_dir.mkdir(parents=True)
        (skills_dir / "naming-conventions.md").write_text(
            "<!-- Generated by skillgen v0.2.0 -->\n---\nname: naming\n---\ncontent",
            encoding="utf-8",
        )
        (skills_dir / "error-handling.md").write_text(
            "<!-- Generated by skillgen v0.2.0 -->\n---\nname: error\n---\ncontent",
            encoding="utf-8",
        )
        (skills_dir / "custom-rules.md").write_text("my custom rules", encoding="utf-8")

        generation = _make_generation(PatternCategory.NAMING)
        write_skills(generation, tmp_path, OutputFormat.CLAUDE)

        assert not (skills_dir / "naming-conventions.md").exists()
        assert not (skills_dir / "error-handling.md").exists()
        assert (skills_dir / "custom-rules.md").exists()

    def test_dry_run_does_not_delete_old_files(self, tmp_path: Path) -> None:
        skills_dir = tmp_path / ".claude" / "skills"
        skills_dir.mkdir(parents=True)
        old_file = skills_dir / "naming-conventions.md"
        old_file.write_text("<!-- Generated by skillgen v0.2.0 -->", encoding="utf-8")
        generation = _make_generation(PatternCategory.NAMING)
        write_skills(generation, tmp_path, OutputFormat.CLAUDE, dry_run=True)
        assert old_file.exists()


class TestAgentsMdHeadings:
    """Test AGENTS.md heading hierarchy."""

    def test_no_h1_in_category_content(self) -> None:
        generation = _make_generation(PatternCategory.NAMING, PatternCategory.STYLE)
        content = _format_agents_md_section(generation)
        lines = content.split("\n")
        for i, line in enumerate(lines):
            if line.startswith("## "):
                for next_line in lines[i + 1 :]:
                    if next_line.strip() and not next_line.startswith("<!--"):
                        assert not next_line.startswith("# "), (
                            f"Heading inversion in AGENTS.md: '## ...' followed by '{next_line}'"
                        )
                        break

    def test_categories_are_h2_in_agents_md(self) -> None:
        generation = _make_generation(PatternCategory.NAMING)
        content = _format_agents_md_section(generation)
        assert "## Naming Conventions" in content
