"""Write skill files to disk in various formats."""

from __future__ import annotations

import contextlib
import os
import re as _re
import tempfile
from collections.abc import Callable
from datetime import date
from pathlib import Path

from skillgen import __version__
from skillgen.models import (
    GenerationResult,
    OutputFormat,
    SkillDefinition,
    WrittenFile,
)

SKILLGEN_HEADER = "<!-- Generated by skillgen v{version} on {date}. Regenerate with: skillgen . -->"
AGENTS_MD_START = "<!-- skillgen:start -->"
AGENTS_MD_END = "<!-- skillgen:end -->"


def write_skills(
    generation: GenerationResult,
    target_dir: Path,
    output_format: OutputFormat,
    dry_run: bool = False,
) -> list[WrittenFile]:
    """Write generated skills to disk. Returns list of WrittenFile records."""
    written: list[WrittenFile] = []

    if output_format in (OutputFormat.CLAUDE, OutputFormat.ALL):
        written.extend(_write_claude_skills(generation, target_dir, dry_run))

    if output_format in (OutputFormat.CURSOR, OutputFormat.ALL):
        written.extend(_write_cursor_skills(generation, target_dir, dry_run))

    if output_format == OutputFormat.ALL:
        written.extend(_write_agents_md(generation, target_dir, dry_run))

    return written


def _get_header() -> str:
    """Generate the skillgen header comment."""
    return SKILLGEN_HEADER.format(version=__version__, date=date.today().isoformat())


def _write_skill_files(
    generation: GenerationResult,
    target_dir: Path,
    dry_run: bool,
    subpath: tuple[str, ...],
    suffix: str,
    format_name: str,
    formatter: Callable[[SkillDefinition], str],
) -> list[WrittenFile]:
    """Write skill files to a subdirectory with the given suffix and formatter."""
    out_dir = target_dir.joinpath(*subpath)
    if not dry_run:
        out_dir.mkdir(parents=True, exist_ok=True)
        _cleanup_orphans(out_dir, generation, suffix=suffix)

    written: list[WrittenFile] = []
    for skill in generation.skills:
        file_path = out_dir / f"{skill.name}{suffix}"
        content = formatter(skill)
        if not dry_run:
            _atomic_write(file_path, content)
        written.append(
            WrittenFile(
                path=file_path,
                format=format_name,
                line_count=content.count("\n") + 1,
                dry_run=dry_run,
            )
        )
    return written


def _write_claude_skills(
    generation: GenerationResult, target_dir: Path, dry_run: bool
) -> list[WrittenFile]:
    """Write .claude/skills/project-conventions/SKILL.md combined file."""
    skills_dir = target_dir / ".claude" / "skills"
    out_dir = skills_dir / "project-conventions"

    if not dry_run:
        out_dir.mkdir(parents=True, exist_ok=True)
        _cleanup_old_flat_skills(skills_dir)

    content = _format_combined_claude_skill(generation)
    file_path = out_dir / "SKILL.md"

    if not dry_run:
        _atomic_write(file_path, content)

    return [
        WrittenFile(
            path=file_path,
            format="claude",
            line_count=content.count("\n") + 1,
            dry_run=dry_run,
        )
    ]


def _write_cursor_skills(
    generation: GenerationResult, target_dir: Path, dry_run: bool
) -> list[WrittenFile]:
    """Write .cursor/rules/<name>.mdc files."""
    return _write_skill_files(
        generation,
        target_dir,
        dry_run,
        subpath=(".cursor", "rules"),
        suffix=".mdc",
        format_name="cursor",
        formatter=_format_cursor_skill,
    )


def _write_agents_md(
    generation: GenerationResult, target_dir: Path, dry_run: bool
) -> list[WrittenFile]:
    """Write or update AGENTS.md at the repo root."""
    agents_path = target_dir / "AGENTS.md"
    new_section = _format_agents_md_section(generation)

    if agents_path.exists():
        try:
            existing = agents_path.read_text(encoding="utf-8")
            content = _replace_delimited_section(existing, new_section)
        except (OSError, UnicodeDecodeError):
            content = new_section
    else:
        content = new_section

    if not dry_run:
        _atomic_write(agents_path, content)

    return [
        WrittenFile(
            path=agents_path,
            format="agents.md",
            line_count=content.count("\n") + 1,
            dry_run=dry_run,
        )
    ]


def _extract_tier_rules(
    generation: GenerationResult,
) -> tuple[list[str], list[str], list[str]]:
    """Extract ALWAYS/PREFERRED/NEVER rules from generated skill content.

    Returns (always_rules, preferred_rules, never_rules).

    Rules are extracted from bold items in skill content. The tier is determined by:
    - ALWAYS: Rules stated with strong imperative language
    - PREFERRED: Rules with qualifying language
    - NEVER: Rules starting with "Do NOT" or "Do not"
    """
    always: list[str] = []
    preferred: list[str] = []
    never: list[str] = []

    for skill in generation.skills:
        for line in skill.content.split("\n"):
            line = line.strip()
            # Extract bold rules: "- **Rule text**" or "- **Rule text** extra"
            m = _re.match(r"^-\s+\*\*(.+?)\*\*", line)
            if not m:
                continue
            rule = m.group(1).strip()

            # Skip non-actionable entries (config values, tool names)
            if (
                rule.startswith("Configured in")
                or rule.startswith("ruff")
                or rule.startswith("Prettier")
            ):
                continue

            # Categorize
            if rule.lower().startswith("do not") or rule.lower().startswith("do not"):
                never.append(rule)
            elif any(word in rule.lower() for word in ["optional", "when applicable", "consider"]):
                preferred.append(rule)
            else:
                always.append(rule)

    # Deduplicate while preserving order
    always = list(dict.fromkeys(always))
    preferred = list(dict.fromkeys(preferred))
    never = list(dict.fromkeys(never))

    # Cap at reasonable limits to keep context window efficient
    return always[:15], preferred[:10], never[:10]


def _format_combined_claude_skill(generation: GenerationResult) -> str:
    """Format all skills into a single combined SKILL.md for Claude Code."""
    header = _get_header()

    # Collect unique glob patterns across all skills.
    all_globs: list[str] = []
    seen: set[str] = set()
    for skill in generation.skills:
        for g in skill.glob_patterns:
            if g not in seen and g != "*":
                all_globs.append(g)
                seen.add(g)
    paths_str = ", ".join(all_globs) if all_globs else "*"

    description = (
        "Apply this project's coding conventions when writing or modifying source code. "
        "Covers naming, error handling, testing, imports, documentation, architecture, "
        "code style, and logging patterns."
    )

    frontmatter = f"""---
name: project-conventions
description: {description}
user-invocable: false
paths: "{paths_str}"
---"""

    lines: list[str] = [
        header,
        "",
        frontmatter,
        "",
        "# Project Conventions",
        "",
    ]

    # Build ALWAYS/PREFERRED/NEVER summary from skill content
    always_rules, preferred_rules, never_rules = _extract_tier_rules(generation)

    if always_rules:
        lines.append("## ALWAYS")
        lines.append("")
        for rule in always_rules:
            lines.append(f"- {rule}")
        lines.append("")

    if never_rules:
        lines.append("## NEVER")
        lines.append("")
        for rule in never_rules:
            lines.append(f"- {rule}")
        lines.append("")

    if preferred_rules:
        lines.append("## PREFERRED")
        lines.append("")
        for rule in preferred_rules:
            lines.append(f"- {rule}")
        lines.append("")

    # Full category details
    lines.append("## Category Details")
    lines.append("")

    for skill in generation.skills:
        lines.append(f"### {skill.category.display_name}")
        lines.append("")
        lines.append(skill.content)
        lines.append("")

    return "\n".join(lines)


def _format_cursor_skill(skill: SkillDefinition) -> str:
    """Format a skill for Cursor (.cursor/rules/*.mdc)."""
    header = _get_header()
    globs_str = ", ".join(skill.glob_patterns) if skill.glob_patterns else "*"
    always_apply = "true" if skill.always_apply else "false"
    frontmatter = f"""---
description: {skill.description}
globs: {globs_str}
alwaysApply: {always_apply}
---"""
    return f"{header}\n\n{frontmatter}\n\n{skill.content}\n"


def _format_agents_md_section(generation: GenerationResult) -> str:
    """Format the AGENTS.md content between delimiters."""
    header = _get_header()
    lines: list[str] = [
        AGENTS_MD_START,
        header,
        "",
        "# AI Agent Guidelines",
        "",
        "The following sections describe this project's conventions and patterns.",
        "Generated automatically by [skillgen](https://github.com/skillgen/skillgen).",
        "",
    ]

    # Add tier summary
    always_rules, preferred_rules, never_rules = _extract_tier_rules(generation)

    if always_rules:
        lines.append("## ALWAYS")
        lines.append("")
        for rule in always_rules:
            lines.append(f"- {rule}")
        lines.append("")

    if never_rules:
        lines.append("## NEVER")
        lines.append("")
        for rule in never_rules:
            lines.append(f"- {rule}")
        lines.append("")

    if preferred_rules:
        lines.append("## PREFERRED")
        lines.append("")
        for rule in preferred_rules:
            lines.append(f"- {rule}")
        lines.append("")

    for skill in generation.skills:
        lines.append(f"## {skill.category.display_name}")
        lines.append("")
        lines.append(skill.content)
        lines.append("")

    lines.append(AGENTS_MD_END)
    return "\n".join(lines)


def _atomic_write(path: Path, content: str) -> None:
    """Write content to a temp file, then atomically rename to target path."""
    dir_path = path.parent
    fd, tmp_path = tempfile.mkstemp(dir=str(dir_path), suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(content)
        os.replace(tmp_path, str(path))
    except BaseException:
        with contextlib.suppress(OSError):
            os.unlink(tmp_path)
        raise


def _cleanup_orphans(directory: Path, generation: GenerationResult, suffix: str) -> list[Path]:
    """Remove generated files from previous runs that are no longer applicable."""
    removed: list[Path] = []
    current_names = {f"{s.name}{suffix}" for s in generation.skills}

    if not directory.is_dir():
        return removed

    for entry in directory.iterdir():
        if entry.is_file() and entry.suffix == suffix and entry.name not in current_names:
            # Check if it was generated by skillgen
            try:
                content = entry.read_text(encoding="utf-8")
                if "Generated by skillgen" in content:
                    entry.unlink()
                    removed.append(entry)
            except (OSError, UnicodeDecodeError):
                pass

    return removed


def _cleanup_old_flat_skills(skills_dir: Path) -> list[Path]:
    """Remove old flat .claude/skills/<name>.md files from previous skillgen versions."""
    removed: list[Path] = []
    if not skills_dir.is_dir():
        return removed

    for entry in skills_dir.iterdir():
        if entry.is_file() and entry.suffix == ".md" and entry.name != "SKILL.md":
            try:
                content = entry.read_text(encoding="utf-8")
                if "Generated by skillgen" in content:
                    entry.unlink()
                    removed.append(entry)
            except (OSError, UnicodeDecodeError):
                pass

    return removed


def _replace_delimited_section(existing: str, new_section: str) -> str:
    """Replace content between skillgen markers, or append if markers not found."""
    start_idx = existing.find(AGENTS_MD_START)
    end_idx = existing.find(AGENTS_MD_END)

    if start_idx != -1 and end_idx != -1:
        end_idx += len(AGENTS_MD_END)
        return existing[:start_idx] + new_section + existing[end_idx:]
    else:
        # Append at end
        separator = "\n\n" if existing.strip() else ""
        return existing + separator + new_section + "\n"
